### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by mapehe** [perej1/hill_simu#1]
Moi, yritin ajaa `python hillSim.py`, ja scripti tuotti seuraavan tulosteen

>hillSim.py:43: RuntimeWarning: divide by zero encountered in power
  return np.power(estimate,-1)
Traceback (most recent call last):
  File "hillSim.py", line 184, in <module>
    main()
  File "hillSim.py", line 155, in main
    plt.hist(N, 50)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 3132, in hist
    stacked=stacked, normed=normed, data=data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 1855, in inner
    return func(ax, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 6530, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 670, in histogram
    'range parameter must be finite.')
ValueError: range parameter must be finite.

**Comment by mapehe** [comment]
#2 pitäisi kattaa tämä
